CREATE DATABASE IF NOT EXISTS `bill`;
CREATE USER IF NOT EXISTS 'bill'@'%' IDENTIFIED BY PASSWORD '*29A1BB43D3B9EB42028B4566E4836353285B9395';
GRANT CREATE ROUTINE, CREATE TEMPORARY TABLES, LOCK TABLES, ALTER, CREATE, CREATE VIEW, DELETE, DELETE HISTORY, DROP, INDEX, INSERT, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE ON bill.* TO 'bill'@'%';
