services:

  db:
    image: mariadb
    restart: always
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: docker
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
